-- =========================================
-- V1__initial_schema.sql
-- VERSÃO FINAL E CORRIGIDA (ALL BIGINT)
-- =========================================

-- =============================
-- TABLE: audit_log
-- =============================
CREATE TABLE public.audit_log (
    id BIGSERIAL PRIMARY KEY, -- Corrigido para BigInt
    table_name TEXT NOT NULL,
    operation TEXT NOT NULL,
    old_data JSONB,
    new_data JSONB,
    executed_at TIMESTAMP DEFAULT now()
);

ALTER TABLE public.audit_log OWNER TO admin_reservas123;


-- =============================
-- TABLE: customers
-- =============================
CREATE TABLE public.customers (
    id BIGSERIAL PRIMARY KEY, -- Corrigido para BigInt
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    phone_number VARCHAR(20),
    cpf VARCHAR(14) UNIQUE,
    passport_number VARCHAR(30),
    birth_date DATE NOT NULL,
    preferred_language VARCHAR(2) DEFAULT 'pt',
    country_origin VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    notes TEXT,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(500)
);

ALTER TABLE public.customers OWNER TO admin_reservas123;


-- =============================
-- TABLE: units
-- =============================
CREATE TABLE public.units (
    id BIGSERIAL PRIMARY KEY, -- Corrigido para BigInt
    name VARCHAR(50) NOT NULL,
    parent_id BIGINT,
    capacity INT NOT NULL,
    default_price NUMERIC(10,2),
    description TEXT,
    area_m2 NUMERIC(10,2),
    city VARCHAR(100),
    state VARCHAR(50),
    address VARCHAR(255),
    airbnb_url VARCHAR(500),
    CONSTRAINT fk_units_parent FOREIGN KEY (parent_id) REFERENCES public.units(id)
);

ALTER TABLE public.units OWNER TO admin_reservas123;


-- =============================
-- TABLE: unit_images
-- =============================
CREATE TABLE public.unit_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- BigInt
    url TEXT NOT NULL,
    unit_id BIGINT NOT NULL,
    CONSTRAINT fk_unit_images_unit
        FOREIGN KEY (unit_id)
        REFERENCES public.units (id)
        ON DELETE CASCADE
);

CREATE INDEX idx_unit_images_unit_id ON public.unit_images(unit_id);
ALTER TABLE public.unit_images OWNER TO admin_reservas123;


-- =============================
-- TABLE: reservations
-- =============================
CREATE TABLE public.reservations (
    id BIGSERIAL PRIMARY KEY, -- <--- O ERRO ESTAVA AQUI (AGORA CORRIGIDO)
    booking_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    check_in DATE NOT NULL,
    check_out DATE NOT NULL,
    total_amount NUMERIC(10,2) NOT NULL,
    status VARCHAR(20) DEFAULT 'PENDING',
    payment_status VARCHAR(20) DEFAULT 'UNPAID',
    customer_id BIGINT NOT NULL,
    unit_id BIGINT NOT NULL,
    origin VARCHAR(20) DEFAULT 'SITE',
    external_uid VARCHAR(255) UNIQUE,
    CONSTRAINT fk_reservations_customer FOREIGN KEY (customer_id) REFERENCES public.customers(id),
    CONSTRAINT fk_reservations_unit FOREIGN KEY (unit_id) REFERENCES public.units(id)
);

CREATE INDEX idx_reservations_customer_id ON public.reservations(customer_id);
CREATE INDEX idx_reservations_unit_id ON public.reservations(unit_id);
CREATE INDEX idx_reservations_dates ON public.reservations(check_in, check_out);

ALTER TABLE public.reservations OWNER TO admin_reservas123;


-- =============================
-- TABLE: reservations_audit
-- =============================
CREATE TABLE public.reservations_audit (
    audit_id BIGSERIAL PRIMARY KEY, -- Corrigido para BigInt
    original_reservation_id BIGINT, -- Corrigido para BigInt
    customer_id BIGINT,
    unit_id BIGINT,
    check_in DATE,
    check_out DATE,
    total_amount NUMERIC(10,2),
    status VARCHAR(20),
    deleted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    operation VARCHAR(10) DEFAULT 'DELETE'
);

ALTER TABLE public.reservations_audit OWNER TO admin_reservas123;


-- =============================
-- TABLE: daily_pricing
-- =============================
CREATE TABLE public.daily_pricing (
    id BIGSERIAL PRIMARY KEY, -- Corrigido para BigInt
    date DATE NOT NULL,
    price NUMERIC(10,2) NOT NULL,
    is_available BOOLEAN DEFAULT TRUE NOT NULL,
    competitor_price NUMERIC(10,2),
    reason VARCHAR(50),
    unit_id BIGINT NOT NULL,
    CONSTRAINT daily_pricing_date_unit_id_key UNIQUE (date, unit_id),
    CONSTRAINT fk_daily_pricing_unit FOREIGN KEY (unit_id) REFERENCES public.units(id)
);

CREATE INDEX idx_daily_pricing_unit_id ON public.daily_pricing(unit_id);

ALTER TABLE public.daily_pricing OWNER TO admin_reservas123;


-- =============================
-- TABLE: reviews
-- =============================
CREATE TABLE public.reviews (
    id BIGSERIAL PRIMARY KEY, -- Já estava correto, mantido.
    rating INT NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    unit_id BIGINT NOT NULL,
    customer_id BIGINT NOT NULL,
    CONSTRAINT fk_reviews_customer FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE CASCADE,
    CONSTRAINT fk_reviews_unit FOREIGN KEY (unit_id) REFERENCES public.units(id) ON DELETE CASCADE
);

CREATE INDEX idx_reviews_unit_id ON public.reviews(unit_id);

ALTER TABLE public.reviews OWNER TO admin_reservas123;


-- =============================
-- FUNCTION: fn_audit_log
-- =============================
CREATE OR REPLACE FUNCTION public.fn_audit_log()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        INSERT INTO audit_log (table_name, operation, new_data)
        VALUES (TG_TABLE_NAME, TG_OP, row_to_json(NEW)::jsonb);
        RETURN NEW;

    ELSIF TG_OP = 'UPDATE' THEN
        INSERT INTO audit_log (table_name, operation, old_data, new_data)
        VALUES (TG_TABLE_NAME, TG_OP, row_to_json(OLD)::jsonb, row_to_json(NEW)::jsonb);
        RETURN NEW;

    ELSIF TG_OP = 'DELETE' THEN
        INSERT INTO audit_log (table_name, operation, old_data)
        VALUES (TG_TABLE_NAME, TG_OP, row_to_json(OLD)::jsonb);
        RETURN OLD;
    END IF;
END;
$$;

ALTER FUNCTION public.fn_audit_log() OWNER TO admin_reservas123;


-- =============================
-- FUNCTION: log_reservation_deletion
-- =============================
CREATE OR REPLACE FUNCTION public.log_reservation_deletion()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO reservations_audit (
        original_reservation_id,
        customer_id,
        unit_id,
        check_in,
        check_out,
        total_amount,
        status,
        deleted_at
    )
    VALUES (
        OLD.id,
        OLD.customer_id,
        OLD.unit_id,
        OLD.check_in,
        OLD.check_out,
        OLD.total_amount,
        OLD.status,
        NOW()
    );

    RETURN OLD;
END;
$$;

ALTER FUNCTION public.log_reservation_deletion() OWNER TO admin_reservas123;


-- =============================
-- TRIGGER
-- =============================
CREATE TRIGGER trg_audit_reservations_delete
AFTER DELETE ON public.reservations
FOR EACH ROW
EXECUTE FUNCTION public.log_reservation_deletion();