ALTER TABLE units
ADD COLUMN wifi BOOLEAN DEFAULT FALSE,
ADD COLUMN pool BOOLEAN DEFAULT FALSE,
ADD COLUMN parking BOOLEAN DEFAULT FALSE,
ADD COLUMN air_conditioning BOOLEAN DEFAULT FALSE,
ADD COLUMN bbq_grill BOOLEAN DEFAULT FALSE; -- Churrasqueira